### ISSUE TITLE
研究室追加依頼

### ISSUE THREAD

**Issue by gyu-don** [ikkoham/qinfoinfo#38]
私の出身研究室と、当時いた人たちの所属先です。追加の検討をお願いします。
量子光学ですが、いわゆる光連続量よりは、単光子などを扱っています。

# 東北大学
## 工学部 電気情報物理工学科 電子工学コース 工学研究科 電子工学専攻 電気通信研究所 量子光情報工学研究室 (枝松 圭一)
- 研究分野: 量子情報・量子光学
- http://www.quantum.riec.tohoku.ac.jp/index.html

枝松先生はQ-leapの基礎基盤研究「光子数識別量子ナノフォトニクスの創成」研究代表者を務められています。

# 電気通信大学(大学院)
## 情報理工学研究科 基盤理工学専攻 清水研究室(清水 亮介)
- 研究分野: 量子情報通信・量子光学
- http://rs.pc.uec.ac.jp/

清水先生はQ-leapの基礎基盤研究「複雑分子系としての光合成機能の解明に向けた多次元量子もつれ分光技術の開発」研究代表者を務められています。

ご検討、よろしくお願いいたします。

**Comment by ikkoham** [comment]
ありがとうございます。
すぐに対応できそうにないですが、こちら追加します。
